{% set name = "gemviz" %}
{% set version = "1.0.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d327b0a6fbee51f83ab2d4578b9513a4fe96bc30ed0365ec1b5518aaeba42ff3

build:
  entry_points:
    - gemviz = gemviz.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }},<=3.12
    - bluesky-tiled-plugins
    - matplotlib-base
    - pyqt =5
    - pyresttable
    - scipy
    - tiled

test:
  imports:
    - gemviz
  commands:
    - pip check
    - gemviz --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://bcda-aps.github.io/gemviz/
  license: BSD-4-Clause
  license_file: gemviz/LICENSE
  summary: Visualize Bluesky data from tiled server.

extra:
  recipe-maintainers:
    - prjemian
    - rodolakis
