{% set name = "gemviz" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3aeca53cbcbd89daea7a8a38b572ee036d83db1119439a39085f6160309eeabc

build:
  entry_points:
    - gemviz = gemviz.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }},<=3.12
    - bluesky-tiled-plugins
    - matplotlib-base
    - pyqt =5
    - pyresttable
    - scipy
    - tiled

test:
  imports:
    - gemviz
  commands:
    - pip check
    - gemviz --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://bcda-aps.github.io/gemviz/
  license: BSD-4-Clause
  license_file: gemviz/LICENSE
  summary: Visualize Bluesky data from tiled server.

extra:
  recipe-maintainers:
    - prjemian
    - rodolakis
