{% set name = "gemviz" %}
{% set version = "0.1.1rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73c72e973671071d713219cd61442e93224c958a7156475160f4f2cc9340046b

build:
  entry_points:
    - gemviz = gemviz.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    # - python {{ python_min }}
    - python 3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    # - python >={{ python_min }},<=3.12
    - python >=3.11,<=3.12
    - matplotlib-base
    - pyqt =5
    - pyresttable
    - tiled

test:
  imports:
    - gemviz
  commands:
    - pip check
    - gemviz --help
  requires:
    - pip
    # - python {{ python_min }}
    - python 3.11

about:
  home: https://bcda-aps.github.io/gemviz/
  license: BSD-4-Clause
  license_file: gemviz/LICENSE
  summary: Visualize Bluesky data from tiled server.

extra:
  recipe-maintainers:
    - prjemian
    - rodolakis
