{% set name = "gemviz" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 818f92880a8bf5b65f737fbdb757f91ac8a87b169404aaf0acd4877c0f536628

build:
  entry_points:
    - gemviz = gemviz.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }},<=3.12
    - bluesky-tiled-plugins
    - matplotlib-base
    - pyqt =5
    - pyresttable
    - scipy
    - tiled

test:
  imports:
    - gemviz
  commands:
    - pip check
    - gemviz --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://bcda-aps.github.io/gemviz/
  license: BSD-4-Clause
  license_file: gemviz/LICENSE
  summary: Visualize Bluesky data from tiled server.

extra:
  recipe-maintainers:
    - prjemian
    - rodolakis
