{% set name = "gemviz" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 740b4be1938320efd84ab6845aadaeb71c3047de1c927625613539e30b6e844a

build:
  entry_points:
    - gemviz = gemviz.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8,<3.12
    - matplotlib-base
    - pyqt =5
    - pyresttable
    - tiled

test:
  imports:
    - gemviz
  commands:
    - pip check
    - gemviz --help
  requires:
    - pip

about:
  home: https://bcda-aps.github.io/gemviz/
  license: BSD-4-Clause
  license_file: gemviz/LICENSE
  summary: Visualize Bluesky data from tiled server.

extra:
  recipe-maintainers:
    - prjemian
    - rodolakis
